[build]
  command = "npm run build"
  publish = "build"

[context.dev.environment]
  REACT_APP_SERVICE_URL = "https://gjv3pd3kck.execute-api.us-east-1.amazonaws.com/dev/sendMail"

[context.production.environment]
  REACT_APP_SERVICE_URL = "https://7zhegm7i9b.execute-api.us-east-1.amazonaws.com/prod/sendMail"